### ISSUE TITLE
image preprocess code

### ISSUE THREAD

**Issue by AlphaJia** [Beckschen/TransUNet#10]
Thanks for your great contribution！
Would u like to share your image preprocess code, that is get 3D image normalize and ertract 2D from 3D and then save to .npz file
Thanks !

**Comment by Beckschen** [comment]
Hello, unfortunately there is no preprocessing code in this repo. But you can send an email (pls using gmail) to jienengchen01 AT gmail to get the access of preprocessed data directly.

**Comment by AlphaJia** [comment]
Thanks for your reply. 
Actually I want to train base on my own 3D dataset. Now I have change the dataset to online dataset_synapse.py script to online preprocess image, that is normalize image and extract 2D from 3D array.
Now it works well!

**Comment by Resse715** [comment]
Hi！Can you share your popocess code? Thanks!

**Comment by hdnminh** [comment]
Hi @Resse715 Do you have the preprocess code, please share with me. Thanks in advance
