### ISSUE TITLE
Wrong Position Embedding Size 

### ISSUE THREAD

**Issue by Siyuan89** [Beckschen/TransUNet#13]
In the original implementation, the position embedding has a dimension of  [ n_patches+1, hidden_size] to accommodate for additional class token:

https://github.com/jeonsworld/ViT-pytorch/blob/a786151f6ceed00e97ab526772916faec5efb8ed/models/modeling.py#L150

In your implementation, you removed the class token and your position embedding has a dimention [ n_patches, hidden_size]:

https://github.com/Beckschen/TransUNet/blob/main/networks/vit_seg_modeling.py#L149

When I tried to load the pre-trained model based on your changes (the new size) , I get a mismatch error:

`    model.load_from(np.load(args.pretrained_dir)), in load_from
    self.transformer.embeddings.position_embeddings.copy_(np2th(posemb))
RuntimeError: The size of tensor a (196) must match the size of tensor b (170) at non-singleton dimension 1`

Would you please explain how the pretrained checkpoint can be loaded based on these changes  ?

**Comment by Beckschen** [comment]
Hello, [line 412-414](https://github.com/Beckschen/TransUNet/blob/main/networks/vit_seg_modeling.py) shows how to adapt the token length from pre-trained weight to the current model. I am also curious why you get a size of (170).

**Comment by Siyuan89** [comment]
Unfortunately I still get this error. The lines you mentioned are also in the original implementation but the sizes seem different, with yours removing the classification token.
