### ISSUE TITLE
Where is the Label Folder located?

### ISSUE THREAD

**Issue by maryamag85** [Beckschen/TransUNet#2]
Hi. In the data section , you have not mentioned where is the ground truth folder?

**Comment by Beckschen** [comment]
Hello,  

For each sample, both image and the corresponding ground truth are stored in the same file (npz format for 2D slice sample or h5py format for 3D volume sample).

Line 60-69 in './datasets/dataset_synapse.py' show that both image and label are read from the same file, regarding the same sample.

I hope this answer can help you. Cheers.
