### ISSUE TITLE
ModuleNotFoundError: No module named 'datasets.dataset_synapse'

### ISSUE THREAD

**Issue by andife** [Beckschen/TransUNet#20]
Hello,
I use the preprocessed data (requested as mentioned in the Readme) and get the 
following error:

TransUNet$ python test.py --dataset Synapse --vit_name R50-ViT-B_16
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    from datasets.dataset_synapse import Synapse_dataset
ModuleNotFoundError: No module named 'datasets.dataset_synapse'

For me, the cause of this is unclear. Does anyone have an idea?

**Comment by Beckschen** [comment]
Hello. It seems that root path of the project is the current path of filefolder, and you cannot import the folder of 'datasets'. 

I am not sure if you have to add the following code in test.py:

current_dir = os.path.abspath(os.path.dirname(__file__))
sys.path.append(current_dir)
import dataset_synapse


Let me know if you have further questions!  Thanks!

**Comment by andife** [comment]
Thank you. I solved the problem. I had a problem adding the project root dir to the the PYHONPATH. Now it works.
