### ISSUE TITLE
AttributeError: "'skip_channels'"

### ISSUE THREAD

**Issue by wangfan120** [Beckschen/TransUNet#21]
Hi,
When I run the test.py , I get the following error:

 ` File "/home/wf/anaconda3/envs/trunet/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 883, in __getitem__
    field = self._fields[key]
KeyError: 'skip_channels'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wf/anaconda3/envs/trunet/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 807, in __getattr__
    return self[attribute]
  File "/home/wf/anaconda3/envs/trunet/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 889, in __getitem__
    raise KeyError(self._generate_did_you_mean_message(key, str(e)))
KeyError: "'skip_channels'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wf/anaconda3/envs/project_TransUNet_2/project_TransUNet/TransUNet/test.py", line 118, in <module>
    net = ViT_seg(config_vit, img_size=args.img_size, num_classes=config_vit.n_classes).cuda()
  File "/home/wf/anaconda3/envs/project_TransUNet_2/project_TransUNet/TransUNet/networks/vit_seg_modeling.py", line 378, in __init__
    self.decoder = DecoderCup(config)
  File "/home/wf/anaconda3/envs/project_TransUNet_2/project_TransUNet/TransUNet/networks/vit_seg_modeling.py", line 343, in __init__
    skip_channels = self.config.skip_channels
  File "/home/wf/anaconda3/envs/trunet/lib/python3.7/site-packages/ml_collections/config_dict/config_dict.py", line 809, in __getattr__
    raise AttributeError(e)
AttributeError: "'skip_channels'"`

Then I change skip_channels = self.config.skip_channels (in vit_seg_modeling.py 343 line) to skip_channels = [512,256,64,16] , I get the following new error:

`RuntimeError: Error(s) in loading state_dict for VisionTransformer:
Unexpected key(s) in state_dict: "transformer.embeddings.hybrid_model.root.conv.weight",
size mismatch for transformer.embeddings.patch_embeddings.weight: copying a param with shape torch.Size([768, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([768, 3, 16, 16])`

For me, the cause of this is unclear. Does anyone have an idea?

**Comment by Rustastra** [comment]
How have you solved it? Thanks!

**Comment by stefenmax** [comment]
I got the same error that  Missing key(s) in state_dict: "transformer.embeddings.position_embeddings", bla bla

Do u fix its problem?

thanks!

**Comment by liyiersan** [comment]
> I got the same error that Missing key(s) in state_dict: "transformer.embeddings.position_embeddings", bla bla
> 
> Do u fix its problem?
> 
> thanks!

I got the same error as you met, have you solved it? Thanks.

**Comment by liyiersan** [comment]
> I got the same error that Missing key(s) in state_dict: "transformer.embeddings.position_embeddings", bla bla
> 
> Do u fix its problem?
> 
> thanks!

I have solved it. You can do it in 3 ways as https://blog.csdn.net/qq_32998593/article/details/89343507
The easiest way to solve it is that before net.load_state_dict(torch.load(snapshot)), you should use nn.DataParallel.
That is:
```python
    net = nn.DataParallel(net)
    net.load_state_dict(torch.load(snapshot))
```

**Comment by stefenmax** [comment]
Thanks anyway!

**Comment by fmd233** [comment]
@wangfan120 I got the same error as you met, have you solved it? Thanks.

**Comment by liyiersan** [comment]
> @wangfan120 I got the same error as you met, have you solved it? Thanks.

If you use vit_name R50-ViT-B_16 to train, then you need to use vit_name R50-ViT-B_16 to test. Check whether the model name is same during training and testing.

**Comment by fmd233** [comment]
@liyiersan Thanks！This error has been resolved.

**Comment by fmd233** [comment]
@liyiersan 
Traceback (most recent call last):
  File "C:/Users/admin/Desktop/project_TransUNet/TransUNet/test.py", line 122, in <module>
    net.load_state_dict(torch.load(snapshot))
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 581, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '../model/TU_Synapse224/TU_pretrain_R50-ViT-B_16_skip3_bs24_224\\epoch_29.pth'
There is no epoch_29.pth in the results of my trained.

**Comment by liyiersan** [comment]
During testing, the default value of max_epoch and batch_size shoule be set as the training. Change default value of the max_epoch and batch_size, if you train with the command 'python train.py --dataset Synapse --vit_name R50-ViT-B_16'. TThen the max_epoch should be 300, batch_size should be 24.
![image](https://user-images.githubusercontent.com/35948100/128474482-e9d808b5-97ee-4b97-9016-f7ed4e601be3.png)

**Comment by liyiersan** [comment]
> @liyiersan
> Traceback (most recent call last):
> File "C:/Users/admin/Desktop/project_TransUNet/TransUNet/test.py", line 122, in
> net.load_state_dict(torch.load(snapshot))
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 581, in load
> with _open_file_like(f, 'rb') as opened_file:
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 230, in _open_file_like
> return _open_file(name_or_buffer, mode)
> File "D:\Anaconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 211, in **init**
> super(_open_file, self).**init**(open(name, mode))
> FileNotFoundError: [Errno 2] No such file or directory: '../model/TU_Synapse224/TU_pretrain_R50-ViT-B_16_skip3_bs24_224\epoch_29.pth'
> There is no epoch_29.pth in the results of my trained.

Have you solved it?

**Comment by fmd233** [comment]
@liyiersan Amazing！Thank you very much！

**Comment by liyiersan** [comment]
> @liyiersan Amazing！Thank you very much！

If you have any other problems, you can ask me for help.

**Comment by fmd233** [comment]
@liyiersan  OK！Thanks！

**Comment by fmd233** [comment]
@liyiersan Hello, excuse me. Do you know how to view the image of the test results?Thank you！

**Comment by liyiersan** [comment]
> @liyiersan Hello, excuse me. Do you know how to view the image of the test results?Thank you！

Well, when you get the output of the model during the test, you can get the segmentation map as follows:
`
map = torch.argmax(torch.nn.Softmax(output, dim=1),dim=1) # B 1 H W, values in [0, num_classes-1]
`
After that, supposing B is 1 during the test stage, then the values of map vary from 0 to num_classes-1. You can rescale the values to [0,255] and repeat the channels to 3, and then you can save the map as a RGB image.

**Comment by Janeispower1998** [comment]
> During testing, the default value of max_epoch and batch_size shoule be set as the training. Change default value of the max_epoch and batch_size, if you train with the command 'python train.py --dataset Synapse --vit_name R50-ViT-B_16'. TThen the max_epoch should be 300, batch_size should be 24. ![image](https://user-images.githubusercontent.com/35948100/128474482-e9d808b5-97ee-4b97-9016-f7ed4e601be3.png)

Thanks for your kindly reply, I solved the problem!!

**Comment by HolicAnn** [comment]
@liyiersan hi, I would like to ask how to make my own data set. I use coco to make annotations, then use pixel matrix to make the marked area and non-marked area into mask image, and finally make the original image and mask map into npz. Is this method correct

**Comment by liyiersan** [comment]
@HolicAnn I guess it is correct. Hope it works fine for you. If you encounter problems that do not work properly, it is recommended to rewrite a dataset class to read the data yourself.

**Comment by Louaq** [comment]
@liyiersan Thank you
