### ISSUE TITLE
I have a question about input channel.

### ISSUE THREAD

**Issue by babbu3682** [Beckschen/TransUNet#3]
Hi! i am very interested in your Paper TransUNet and after reading your paper I have a question about input channel.

the medical domain often has 1 channel(gray scale) but ResNetV2 which you proposed treat 3 channel as input 

Did you just simply stack the gray scale image to make 3 channel image?

**Comment by Beckschen** [comment]
Hello,

Thanks for the comment. Yes you are right. Line 386-387 in the [script](https://github.com/Beckschen/TransUNet/blob/main/networks/vit_seg_modeling.py) shows that we simply repeat the gray scale CT/MR image to 3 channels. Btw, the ResNet is adopted from this [repo](https://github.com/jeonsworld/ViT-pytorch), with minor modifications.
