### ISSUE TITLE
Length of each patch vector D

### ISSUE THREAD

**Issue by nviwch** [Beckschen/TransUNet#4]
I am not very familiar with PyTorch but is the config.hidden_size = the length of vector which each patch has, i.e. D = config.hidden_size?

But then I have a question how do you choose the vector length, and while in a 16x16 monochromatic patch there are only 256 numbers why do we need that much more than 256 to represents the patch?

**Comment by Beckschen** [comment]
Hello,

For the question: "the config.hidden_size = the length of vector which each patch has, i.e. D = config.hidden_size?" 
- config.hidden_size is the hidden dimensional of transformer. The length of vector which each patch should be config.patches ^ 2 (e.g. 16*16). 

For the second question, I believe its patch embedding that converts the hidden dimension to config.hidden_size. The patch embedding denotes the linear projection of flattened image patches or feature patches. 

Let me know if you have any questions. Thanks!
