### ISSUE TITLE
Hi, a question about the models' output 

### ISSUE THREAD

**Issue by JoyChen1998** [Beckschen/TransUNet#49]
Thanks for your work. I have some problems about using it for another task. 
I modified the dataloader, my input are  {img (1,3,512,512), label(1,1,512,512) }, but on training phase,  I got the output=model(image_patch) (1,2,512,512), 
when calc loss, caused error `RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [1, 1, 512, 512]`.

args:
vit_name = R50-ViT-B_16, n_skip=3, vit_patches_size=16

  can you give me some advice? thank you!

**Comment by Yujin-Yujin** [comment]
How did you solve this error?

**Comment by JoyChen1998** [comment]
Hi, it may depends on your identified class numbers on vit_set_configs.py ,
the param config.n_classes , I use ` map = map[:, 1, :, :].unsqueeze(1) `
to get the feature map.

Yujin-Yujin ***@***.***> 于2021年12月6日周一 13:48写道：
