### ISSUE TITLE
Request Preprocessed Dataset!

### ISSUE THREAD

**Issue by yangmingming629** [Beckschen/TransUNet#52]
Hello! Could you kindly send the preprocessed dataset? Thank you! 1213198028@qq.com or Baidu disk (ymm4586179). Thanks very much!

**Comment by Prettygirl2021** [comment]
Request prepossessed dataset. My email is 1439402142@qq.com. Thank you so so much!

**Comment by ST-QI** [comment]
Request prepossessed dataset. My email is TqShen@buaa.edu.cn. Thank you so so much!

**Comment by aprilaugust** [comment]
Could you mind sharing your preprocessed dataset (for my educational purpose only)? 
My email is taurus.leo.tw@gmail.com.
Thank you so much in advance!

**Comment by kjp96** [comment]
Hello! Could you kindly send the preprocessed dataset? Thank you! My email is 2018282110400@whu.edu.cn. Thanks very much!

**Comment by zhanghaobucunzai** [comment]
有人获取到数据集了吗  能共享下不？

**Comment by Barrett-python** [comment]
Hello! Could you kindly send the preprocessed dataset? Thank you! My email is Feilong.Tang19@student.xjtlu.edu.cn. Thanks very much!

**Comment by wwjwy** [comment]
Request prepossessed dataset. My email is wwjhhu@gmail.com. Thank you so so much!

**Comment by yezhengjie** [comment]
Hello! Could you kindly send the preprocessed dataset? Thank you! My email is 1303698906@qq.com Thanks very much!

**Comment by zsc1104** [comment]
Request prepossessed dataset. My email is 1336247478@qq.com. Thank you so so much!

**Comment by thithaotran** [comment]
Could you please send me the preprocessed dataset? My email is thaott3i at gmail.com. Thank you!

**Comment by songyang86** [comment]
Request prepossessed dataset. My email is 1335496470@qq.com. Thank you so so much!

**Comment by lycutter** [comment]
Hello! Could you kindly send the preprocessed dataset? Thank you! My email is 479207459@qq.com Thanks very much!

**Comment by melonlc** [comment]
Request prepossessed dataset. My email is 1242552822@qq.com. Thank you so so much!

**Comment by dan326326** [comment]
Hello! Could you  send the preprocessed dataset? Thank you! My email is 1229170243@qq.com Thanks very much!

**Comment by navendano11** [comment]
Hello, I also would like to request the preprocessed data or at least the code. I haven't had any reply on the email jienengchen01 AT gmail.com
