### ISSUE TITLE
Running the test.py module

### ISSUE THREAD

**Issue by SM-93** [Beckschen/TransUNet#8]
Hi! I am very interested in your paper and solution for the medical image segmentation.

Regarding my **first question**, I ran the test.py  and it outputs that there is a problem in line 122 in the code and 
that there is no such file or directory '../model/TU_Synapse224/TU_pretrain_R50-ViT-B_16_skip3_bs24_224/epoch_29.pth'
I hope that you can help me with this problem. 
I did run it on single image though, if that can be some sort of an issue.

**Second question** is, why is there a need to clip an image between [-125, 275] ? Image that I downloaded is grayscale of the uint8 data type.

**Comment by Beckschen** [comment]
Hello,

I think you have to firstly train the model to obtain a snapshot, which will be automatically saved in filefolder such as ''../model/TU_Synapse224/TU_pretrain_R50-ViT-B_16_skip3_bs24_224/'. Afterwards, run the test.py, where the snapshot will be loaded to network and testing data will be inferenced by the network.

Secondly, I don't know if you download the right dataset in Synapse official website, where some files displayed there are not the multi-organ dataset we used. Instead, you have to sign up first and then a filefolder called as abdominal should be the multi-organ dataset. There is an alternative way that you can send an Email to jienengchen01 AT gmail.com to request the preprocessed data.

The reason why we need to clip an orignal CT image is that the HU value in CT images will range from [-1000, 2000] with many redudant information..

**Comment by SM-93** [comment]
Hello Beckschen,
thank you for your detailed response, I really appreciate it.
I found the Abdomen folder after all.
