### ISSUE TITLE
Request for the preprocessed data

### ISSUE THREAD

**Issue by CiuzaakWong** [Beckschen/TransUNet#80]
@Beckschen , Hello, 
I am trying to extend an existing continual semantic segmentation method to be suitable for 3D medical datasets.  The Synapse dataset (Medical Image Segmentation on Synapse multi-organ CT) seems to be a good choice for us to construct further experiments. However, we can not achieve satisfactory baseline performance due to the lack of 3D data preprocessing. It will be very nice if you would like to share the preprocessed data.
My email: vqatpq776@gmail.com

**Comment by 847001315** [comment]
> @Beckschen，你好， 我正在尝试扩展现有的连续实验分割方法以适用 3D 医学数据集。然而，由于缺乏3D数据预处理，我们无法获得令人满意的基线性能。如果您想共享预处理的数据，那将是非常好的。 我的邮箱：[vqatpq776@gmail.com](mailto:vqatpq776@gmail.com)

Did you get a reply?

**Comment by wddwzwhhxx** [comment]
> 
...
Did you get a reply?

**Comment by wddwzwhhxx** [comment]
> > @Beckschen，你好， 我正在尝试扩展现有的连续实验分割方法以适用 3D 医学数据集。然而，由于缺乏3D数据预处理，我们无法获得令人满意的基线性能。如果您想共享预处理的数据，那将是非常好的。 我的邮箱：[vqatpq776@gmail.com](mailto:vqatpq776@gmail.com)
> 
> Did you get a reply?
...
Did you get a reply?
