### ISSUE TITLE
Question about custom dataset

### ISSUE THREAD

**Issue by MyGitHub-G** [Beckschen/TransUNet#90]
Hello，thanks for your nice work.
I have the a question.
I have known that both image and label are read from the same file, but I don't know how the code distinct label from image, 
![屏幕截图 2022-03-31 224221](https://user-images.githubusercontent.com/71758483/161082571-f2ef538e-57d6-4185-8606-3f4dae628e40.png)

there only each slice's name in the "train.txt"
The "train.txt" of one program I did before is [image path & label path], such as:
【xx/xx.png | xx/xx.png】 ,  the " | " is a separator

So the question is that I don't know how to make the "train.txt" of my custom dataset, it's not like the program I did before.
Just let both image and label are read in the same file, and "train.txt" only contains the image path ?
Hope your reply! Thank you!!

**Comment by JAYCHOU2020** [comment]
> Hello，thanks for your nice work. I have the a question. I have known that both image and label are read from the same file, but I don't know how the code distinct label from image, ![屏幕截图 2022-03-31 224221](https://user-images.githubusercontent.com/71758483/161082571-f2ef538e-57d6-4185-8606-3f4dae628e40.png)
> 
> there only each slice's name in the "train.txt" The "train.txt" of one program I did before is [image path & label path], such as: 【xx/xx.png | xx/xx.png】 , the " | " is a separator
> 
> So the question is that I don't know how to make the "train.txt" of my custom dataset, it's not like the program I did before. Just let both image and label are read in the same file, and "train.txt" only contains the image path ? Hope your reply! Thank you!!

did u fix it?
