### ISSUE TITLE
Problem with test performance 

### ISSUE THREAD

**Issue by dianexuli** [Beckschen/TransUNet#97]
Hello, thanks a lot for your work. I have a question about the testing result on Synapse dataset.
I have trained the network with R50-ViT-B_16, and base_lr=0.01, batch_size=24,n_skip=3, img_size=224, max_epochs=300, vit_patches_size=16. The difference with method in paper is: num_classes=14, because there 13 classes and background in Synapse dataset.
After 300 epochs, I use <python test.py --dataset Synapse --vit_name R50-ViT-B_16 --max_epochs 300> to test. However, I got <mean_dice : 0.131854 mean_hd95 : 83.012894>, this is far from the result in paper.
I don't know the reason. Can somebody help me?

**Comment by wangru1026** [comment]
I also encountered the same problem, it has been bothering me for several days, I don't know what is wrong, how to solve this problem, could you tell me, I would be very grateful.

**Comment by wanrat40** [comment]
I have the same problem, can anyone tell me how to solve it, please?
